version: "3.9"
services:
  quakewatch:
    build: .
    image: amirchapi/quakewatch:latest
    container_name: quakewatch-app
    ports:
      - "5000:5000"
    # אחסון מתמשך (רק אם צריך):
    volumes:
      - quakewatch_data:/data
volumes:
  quakewatch_data:
